---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Ingestion Service STAGING
    contact: Chris Perry
  labels:
    env: staging
    name: svc-ingest-initiation-staging
  name: svc-ingest-initiation-staging
  namespace: staging
spec:
  ports:
  - name: http
    targetPort: http
    port: 80
    protocol: TCP
  selector:
    name: svc-ingest-initiation-staging
  type: ClusterIP