---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Ingestion Service DEVELOP
    contact: Chris Perry
  labels:
    env: develop
    name: svc-ingest-initiation-develop
  name: svc-ingest-initiation-develop
  namespace: develop
spec:
  ports:
  - name: http
    targetPort: http
    port: 80
    protocol: TCP
  selector:
    name: svc-ingest-initiation-develop
  type: ClusterIP